  # Position Controllers ---------------------------------------

  panda_left_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_left_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_left_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  panda_right_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  panda_right_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_right_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}

