
gazebo_ros_control:
  pid_gains:
    panda_left_joint1: {p: 50, i: 0, d: 20}
    panda_left_joint2: {p: 10000, i: 0, d: 500}
    panda_left_joint3: {p: 100, i: 0, d: 10}
    panda_left_joint4: {p: 1000, i: 0, d: 50}
    panda_left_joint5: {p: 100, i: 0, d: 10}
    panda_left_joint6: {p: 100, i: 0, d: 10}
    panda_left_joint7: {p: 10, i: 0.5, d: 0.1}
    panda_left_finger_joint1: {p: 100, i: 0, d: 50}
    panda_left_finger_joint2: {p: 100, i: 0, d: 50}
    panda_right_joint1: {p: 50, i: 0, d: 20}
    panda_right_joint2: {p: 10000, i: 0, d: 500}
    panda_right_joint3: {p: 100, i: 0, d: 10}
    panda_right_joint4: {p: 1000, i: 0, d: 50}
    panda_right_joint5: {p: 100, i: 0, d: 10}
    panda_right_joint6: {p: 100, i: 0, d: 10}
    panda_right_joint7: {p: 10, i: 0.5, d: 0.1}
    panda_right_finger_joint1: {p: 100, i: 0, d: 50}
    panda_right_finger_joint2: {p: 100, i: 0, d: 50}
