panda_left_gripper_position_controller:
  type: "effort_controllers/JointGroupPositionController"
  joints:
  - panda_left_finger_joint1
  - panda_left_finger_joint2
  pid_gains:
    panda_left_finger_joint1: {p: 100, i: 0, d: 50}
    panda_left_finger_joint2: {p: 100, i: 0, d: 50}
  

panda_right_gripper_position_controller:
  type: "effort_controllers/JointGroupPositionController"
  joints:
  - panda_right_finger_joint1
  - panda_right_finger_joint2
  pid_gains:
    panda_right_finger_joint1: {p: 100, i: 0, d: 50}
    panda_right_finger_joint2: {p: 100, i: 0, d: 50}