# The joint state controller handles publishing transforms for any moving joints
left/joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

right/joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50