left/joint1_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint1

left/joint2_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint2

left/joint3_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint3

left/joint4_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint4

left/joint5_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint5

left/joint6_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint6

left/joint7_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_left_joint7

left/joint7_effort_controller:
  type: "effort_controllers/JointEffortController"
  joint: panda_left_joint7

right/joint1_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint1

right/joint2_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint2

right/joint3_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint3

right/joint4_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint4

right/joint5_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint5

right/joint6_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint6

right/joint7_position_controller:
  type: "position_controllers/JointPositionController"
  joint: panda_right_joint7

right/joint7_effort_controller:
  type: "effort_controllers/JointEffortController"
  joint: panda_right_joint7